version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: tienda_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: ecommerce_ropa
    ports:
      - "5432:5432"